# Generated by Django 3.1.5 on 2022-04-23 13:32

from django.db import migrations, models
import django.utils.timezone
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_task2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(default=todo.models.slug_default, unique=True, verbose_name='slug')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
        migrations.DeleteModel(
            name='Task2',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Тема'),
        ),
    ]
